services:
  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks: [ node-red-net ]
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  node-red-net:
    external: false
